apiVersion: apps/v1
kind: Deployment
metadata:
  name: flight-pred-api
  labels:
    app: flight-pred-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flight-pred-api
  template:
    metadata:
      labels:
        app: flight-pred-api
    spec:
      containers:
        - name: api
          image: flight-pred-api:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000
          # optional: resource requests/limits
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 256Mi
